### ISSUE TITLE
[RiscV] "No candidates found for (...)" when reading MPT containing BLT instruction

### ISSUE THREAD

**Issue by TheArni** [IBM/microprobe#14] opened 2020-07-09 08:33 UTC
When I try to run the `mp_mpt2c` tool on an MPT file which contains a RiscV BLT instruction the program crashes with the following error: `No candidates found for 0xfaf740e3`

The following options are used: `-T riscv_v22-riscv_generic-riscv64_linux_gcc --fix-indirect-branches --fix-branch-next --fix-memory-registers`.

If we use objdump to decode the actual instruction in the binary we can see it is as follows:

`105d4:       faf740e3                blt     a4,a5,10574 <intVecSum+0x28>`

Attached in this issue there is the debug log output ([log.txt](https://github.com/IBM/microprobe/files/4895458/log.txt)). There you will observe how there is some issue regarding the immediate. From the objdump above we can see how the immediate should be -96, but instead in the attached log microprobe is trying to use -3. I suspect there is a bug in the code in charge of decoding an instruction from binary in which the proper formatting of the instruction is not taken into account. Remember that the "B" format in riscv, which is the one used for this instruction, has some weirdly coded immediate which is not only divided in two subfields but also the bits are not ordered. This suggests that this bug could also happen with other branch-related instructions which use the same format.

### How to reproduce
1. Create an MPT file containing the BLT instruction (one is already attached to this issue: [vecsum.0.mpt.zip](https://github.com/IBM/microprobe/files/4895465/vecsum.0.mpt.zip))
2. Execute the following command: `mp_mpt2c.py -t testfile.mpt -O benchmark.c -T riscv_v22-riscv_generic-riscv64_linux_gcc --fix-indirect-branches --fix-branch-next --fix-memory-registers`

**Comment by rbertran** [comment] 2020-07-09 12:38
Thanks for the report. I was able to reproduce the issue, looking now for a solution.

**Comment by rbertran** [comment] 2020-07-10 06:38
@TheArni Fixes have been implemented to support the correct codification for all the instructions. I realized today that some corners cases where not yet implemented. This went out from my radar since we mainly used RISCV port to generate code, not to interpret existing binaries. 

In the following minutes, once all the CI tests finish, the updates should be populated to the repository. Then you can proceed to update your clone/fork, and make sure you remove any cache files. You can do so by removing the `.*.cache` files in the target directories. Alternatively, you can execute the tool with debug flag (`-d`) and the cache files will be regenerated. 

I don't close the issue yet. I'll wait for you to try more extensive [chopstix ](https://github.com/IBM/chopstix/)generated MPT files and confirm that there are not further issues.

**Comment by TheArni** [comment] 2020-07-15 15:14
Thanks @rbertran for the quick response, we were able to do some progress. The microbenchmark is now getting generated correctly, however there seems to be some sort of issue regarding the fixing of memory addresses. The .c source code is the same which microprobe generates given the scenario above ([benchmark.c](https://github.com/IBM/microprobe/files/4926093/benchmark.txt)). The crash (segfault) happens at the last of the following lines (the `SD` instruction at line 378):

```
367 __asm__(" MEMACCESS_FIX_0_pcrel_1:AUIPC x2, %pcrel_hi(MEMACCESS_FIX_0) ");      
368 __asm__(" ADDI x2, x2, %pcrel_lo(MEMACCESS_FIX_0_pcrel_1) ");                   
369 __asm__(" MEMACCESS_FIX_1_pcrel_2:AUIPC x8, %pcrel_hi(MEMACCESS_FIX_1) ");      
370 __asm__(" ADDI x8, x8, %pcrel_lo(MEMACCESS_FIX_1_pcrel_2) ");                   
371 __asm__(" MEMACCESS_FIX_2_pcrel_3:AUIPC x15, %pcrel_hi(MEMACCESS_FIX_2) ");     
372 __asm__(" ADDI x15, x15, %pcrel_lo(MEMACCESS_FIX_2_pcrel_3) ");                 
373 __asm__(" ADDI x3, x0, 0x0 ");                                                  
374 __asm__(" first:ADDI x0, x2, -0x40 ");                                          
375 __asm__(" ADDI x1, x2, -0x40 ");                                                
376 __asm__(" ADDI x10, x2, -0x40 ");                                               
377 __asm__(" ADDI x11, x2, -0x40 ");                                               
378 __asm__(" SD x8, 0x38(x2) "); 
```
When debugging the execution, one would expect that the `x2` register would point to a region of memory within MEMACCESS_FIX_0 (as is set above in the code), however this is not the case (you can check this by reading the value of `x2` and comparing it to the position of MEMACCES_FIX_0 symbol which can be found by using the `nm` utility). This suggests that maybe the instructions being generated for memory fixing is not right? I'm not sure.

Aside from this, I also noticed some weird code involving writing to the `x0` register, or using "protected" registers such as the stack pointer (which is, precisely, `x2`), etc. I'm not sure if that's intended behavior or not.

If you need any additional information, files, whatever else to solve this issue, please don't hesitate to ask me.

**Comment by rbertran** [comment] 2020-07-15 20:10
ok, one issue solved, let's handle next one ;)

At first sight, I don't detect any issue, x2 is loaded with the address, and then is used with 0x38 displacement, which is within the boundaries of the MEMACCESS_FIX_0 . Since, I'm probably missing something, so I'll need to reproduce and debug. 

To avoid confusion and maintain a specific topic per issue,  please open a separate issue for this new topic and include the command used and the input mpt files so that I can get reproduce the issue and check how the fixing code is generated.  We'll discuss follow up over there.

Regarding this issue, on decoding instruction binaries, I assume that is solved after you testing. Otherwise, feel free to reopen it.

**Closed by rbertran** 2020-07-15 20:10 UTC
