### ISSUE TITLE
Memory addressing

### ISSUE THREAD

**Issue by rgokulsm** [IBM/microprobe#9] opened 2019-12-05 01:29 UTC
This might be more of a general/riscv question than a microprobe specific one - can you provide some insight on what is happening in the code below with respect to the x_i and the 0x7ff... More specifically what is the difference between x2, x3 etc and why are they used. The reason I'm asking is because I hit a page fault (on gem5 syscall emulation mode) when my program has to use multiple x_i for the memory addressing:

.comm ST_1024_64_0, 65600
.comm riscv_v22_scratch_var, 256

/* Start Main */
RVTEST_RV64UF
RVTEST_CODE_BEGIN

reset:ADDI x0, x1, 0x0
**ST_1024_64_0_pcrel:AUIPC **x2**, %pcrel_hi(ST_1024_64_0)
ADDI **x2, x2,** %pcrel_lo(ST_1024_64_0_pcrel)
OR **x2, x2, x3**
ADDI **x3, x3**, 0x7ff
ADDI **x3, x3**, 0x1
OR **x3, x3,** x4**
ADDI x4, x4, 0x7ff
ADDI x4, x4, 0x1
OR x4, x4, x5
ADDI x5, x5, 0x7ff
ADDI x5, x5, 0x1
OR x5, x5, x6
ADDI x6, x6, 0x7ff
ADDI x6, x6, 0x1
OR x6, x6, x7
..................................
..................................
..................................
And later:
LD x20, 0x7c0(**x2**) /* Address: Address((char) ST_1024_64_0[65600]+0x00000000000007c0) */
MUL x22, x21, x0
SD x28, 0x0(**x3**) /* Address: Address((char) ST_1024_64_0[65600]+0x0000000000000800) */
MUL x27, x25, x23

**Comment by rbertran** [comment] 2019-12-05 02:45
**Understanding the code**

These asm lines:
```
ST_1024_64_0_pcrel:AUIPC x2, %pcrel_hi(ST_1024_64_0)
ADDI x2, x2, %pcrel_lo(ST_1024_64_0_pcrel)
```
load the base address of the `ST_1024_64_0` defined at the top of the code to register `x2`. To do so, we use symbolic PC-relative relocations. This is needed because we do not know in advance the position of that array in memory. The program memory layout is defined at link/loading time.  It is also possible to hard-code all addresses and then generate code accordingly, let me know if that is your use-case and I can direct you on how to do so. Then, these lines:
```
OR x2, x2, x3
ADDI x3, x3, 0x7ff
ADDI x3, x3, 0x1
```
add `0x7ff+0x1 = 0x800` displacement to address loaded in register `x2` . So, `x3` should be pointing to address ``ST_1024_64_0+0x800`` . 

**Code generation process**

I've not reproduced the code, but my guess is the following. The memory pass you are using, first needs to initialize a base register pointing to ``ST_1024_64_0`` array (in this case `x2`). This register is going to be _reserved_ so that no other instructions modify it. Whenever the memory pass finds an instruction accessing to memory, it uses that register as a reference (and also sets any other operands as required to access to the target address).  This is what you see in:
```
LD x20, 0x7c0(x2) /* Address: Address((char) ST_1024_64_0[65600]+0x00000000000007c0) /
```
where ``x2`` is used as base register and the immediate operand is used for displacement. Later on, the memory pass wants to generate a reference to ``ST_1024_64_0+0x800`` . However, the maximum operand displacement that one can encode is less than `0x800` . As a result, the algorithm decides to reserve another register (``x3``) and initialize it to ``ST_1024_64_0+0x800`` (this is the code inserted at the top). Then, it uses that new reserved register to generate the load:
```
SD x28, 0x0(x3) / Address: Address((char) ST_1024_64_0[65600]+0x0000000000000800) */
```

**Segmentation fault**

I only see two options that lead to an incorrect code that generates a wrong address (triggering a segmentation fault):

1. The base pointers are not loaded property.  If you fail right away on the first usage (load/store) of the registers used for memory references, that would mean that they are not properly set.  
2. There are some instructions that for some reason modifies the registers used (``x2`` or ``x3``). If you can execute correctly some loads/stores but then the segmentation fault is triggered, that'd mean that some instruction between the last correct load/store and the failing one, modified the contents. 

**Debugging the code correctness**

Not sure how to debug on your setup. If you can stop the simulation at any time and check register/memory contents, I'd look for the particular instruction/memory access triggering the error and then validate what I said before. I need more details on the _gem5 syscall emulation mode_, but I think that the code generated does not generate syscalls. Another thing to point out, is that the code generated does not respect any calling convention because it is assumed to be an endless loop. If that is not the case, then it is possible that weird things happen at program finalization. If you share some details of the GEM5/risc-v methodology (how do you compile, load the binary to the sim, full system?, etc...), I can try to reproduce the issue.

**Debugging the code generation process**

You can use the following environment variables for debugging:

- `MICROPROBEDEBUG=True` to dump everything
- `MICROPROBEDEBUGPASSES=True` to dump everything during the passes (code generation)

**Comment by rgokulsm** [comment] 2019-12-05 22:48
Thanks a lot Ramon - this is a lot of useful notes to think about... I haven't looked into debugging deeper yet, but what I have at the moment is the following:

This code works:

```
.comm ST_1024_64_0, 65600
.comm riscv_v22_scratch_var, 256

/* Start Main */
RVTEST_RV64UF
RVTEST_CODE_BEGIN

reset:ADDI x0, x1, 0x0
ST_1024_64_0_pcrel:AUIPC x2, %pcrel_hi(ST_1024_64_0)
ADDI x2, x2, %pcrel_lo(ST_1024_64_0_pcrel)
/* Building block start */
```

While this hits a page fault (Error: Page table fault when accessing virtual address 0x7ff ):

```
.comm ST_1024_64_0, 65600
.comm riscv_v22_scratch_var, 256

/* Start Main */
RVTEST_RV64UF
RVTEST_CODE_BEGIN

reset:ADDI x0, x1, 0x0
ST_1024_64_0_pcrel:AUIPC x2, %pcrel_hi(ST_1024_64_0)
ADDI x2, x2, %pcrel_lo(ST_1024_64_0_pcrel)
OR x2, x2, x3
ADDI x3, x3, 0x7ff
ADDI x3, x3, 0x1     
OR x3, x3, x4
ADDI x4, x4, 0x7ff
ADDI x4, x4, 0x1
OR x4, x4, x5
ADDI x5, x5, 0x7ff
ADDI x5, x5, 0x1
OR x5, x5, x6
ADDI x6, x6, 0x7ff
ADDI x6, x6, 0x1 
OR x6, x6, x7
ADDI x7, x7, 0x7ff
ADDI x7, x7, 0x1
OR x7, x7, x8
ADDI x8, x8, 0x7ff
ADDI x8, x8, 0x1
OR x8, x8, x9
ADDI x9, x9, 0x7ff
ADDI x9, x9, 0x1
OR x9, x9, x10
ADDI x10, x10, 0x7ff
ADDI x10, x10, 0x1
/* Building block start */
```

Other notes:
I am compiling statically so I don't know how that affects any of the stuff you mentioned at the beginning of your comment. 

>  It is also possible to hard-code all addresses and then generate code accordingly, let me know if that is your use-case and I can direct you on how to do so

--- If this is trivial can you tell me how to do this? Just considering the working vs not-working examples above, maybe doing the hard coding might be a worthy try.

**Comment by rbertran** [comment] 2020-03-11 16:28
In latest updates I fixed some issues here and there and I was able to create a variety of workloads with different memory access patterns successfully. I used different format outputs and validation:

- **RiscvTestsP** wrapper + compile using example riscv test environtment -> validation with spike 
- **CInfGen** wrapper + compile using gcc -static -> validation with qemu-riscv64

It seems that the problem is solved. Let me know if your problem persist, otherwise you can close this issue.

**Comment by rgokulsm** [comment] 2020-04-21 19:08
The issues addressed here were also covered in some other issues (#7 , #10 ) - they all seem to be resolved. Thanks!

**Closed** 2020-04-21 19:08 UTC
